# Generated by Django 2.1.3 on 2018-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='valor_char',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dado',
            name='valor_int',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
