# Generated by Django 2.1.3 on 2018-11-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0002_auto_20181103_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuador_troca_estado',
            name='estado_anterior',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='atuador_troca_estado',
            name='estado_atual',
            field=models.NullBooleanField(default=False),
        ),
    ]
