# Generated by Django 2.1.3 on 2018-11-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0003_auto_20181103_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuador_boolean',
            name='estado',
            field=models.NullBooleanField(default=False),
        ),
    ]
