# Generated by Django 2.1.3 on 2019-01-03 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0004_auto_20181103_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='If_else_sensor_boolean',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarefa.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!=')])),
                ('valor', models.NullBooleanField()),
                ('elsetask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_boolean', to='tarefa.If_else_sensor_boolean')),
            ],
            bases=('tarefa.task',),
        ),
        migrations.CreateModel(
            name='If_else_sensor_dadosensor',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarefa.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!='), (2, '>'), (3, '>='), (4, '<'), (5, '<=')])),
                ('elsetask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_dadosensor', to='tarefa.If_else_sensor_dadosensor')),
            ],
            bases=('tarefa.task',),
        ),
        migrations.CreateModel(
            name='If_else_sensor_numero',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarefa.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!='), (2, '>'), (3, '>='), (4, '<'), (5, '<=')])),
                ('valor', models.IntegerField()),
                ('elsetask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_numero', to='tarefa.If_else_sensor_numero')),
            ],
            bases=('tarefa.task',),
        ),
        migrations.CreateModel(
            name='If_else_sensor_string',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tarefa.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!=')])),
                ('valor', models.CharField(max_length=200)),
                ('elsetask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_string', to='tarefa.If_else_sensor_string')),
            ],
            bases=('tarefa.task',),
        ),
        migrations.AlterField(
            model_name='task',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'save_database'), (1, 'dado_sensor_numero'), (2, 'dado_sensor_string'), (3, 'dados_sensor_media'), (4, 'dado_sensor_min'), (5, 'dado_sensor_max'), (6, 'if_sensor_string'), (7, 'if_sensor_numero'), (8, 'if_sensor_boolean'), (9, 'if_sensor_dadosensor'), (10, 'atuador_troca_estado'), (11, 'atuador_boolean'), (12, 'if_else_sensor_string'), (13, 'if_else_sensor_boolena'), (14, 'if_else_sensor_dadosensor'), (15, 'if_else_sensor_number')], default=0),
        ),
        migrations.AddField(
            model_name='if_else_sensor_dadosensor',
            name='valor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='If_else_sensor_dadosensor', to='tarefa.Task'),
        ),
    ]
