# Generated by Django 2.1.3 on 2019-01-03 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0005_auto_20190103_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anterior', to='tarefa.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_sucessor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sucessor', to='tarefa.Task'),
        ),
    ]
