# Generated by Django 2.1.3 on 2019-01-03 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0006_auto_20190103_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='if_else_sensor_string',
            name='elsetask',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elsetasksensor_string', to='tarefa.Task'),
        ),
    ]
