# Generated by Django 2.1.4 on 2019-01-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0008_auto_20190103_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atuador_troca_estado',
            name='estado_anterior',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='atuador_troca_estado',
            name='estado_atual',
            field=models.BooleanField(default=False),
        ),
    ]
