# Generated by Django 2.0.5 on 2018-06-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=200)),
                ('porta', models.IntegerField(default=1883)),
                ('user', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('estado', models.IntegerField(choices=[(0, 'off'), (1, 'on'), (2, 'running')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dado', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topico', models.CharField(max_length=250)),
                ('broker', models.ForeignKey(on_delete=True, to='mqtt.Broker')),
            ],
        ),
        migrations.AddField(
            model_name='dado',
            name='mqtt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mqtt.Mqtt'),
        ),
    ]
