# Generated by Django 2.0.5 on 2018-06-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='QoS',
            field=models.IntegerField(choices=[(0, 'QoS - 0'), (1, 'QoS - 1'), (2, 'QoS - 2')], default=0),
        ),
    ]
