# Generated by Django 2.0.5 on 2018-10-08 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0002_auto_20181007_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='mqtt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mqtt.Mqtt'),
        ),
    ]
