# Generated by Django 2.0.5 on 2018-10-08 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0003_auto_20181007_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='mqtt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo', to='mqtt.Mqtt'),
        ),
    ]
