# Generated by Django 2.0.5 on 2018-07-10 15:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_auto_20180710_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 10, 15, 20, 18, 407697, tzinfo=utc)),
        ),
    ]
