# Generated by Django 2.0.5 on 2018-07-10 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0005_auto_20180710_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 10, 15, 23, 4, 946034, tzinfo=utc)),
        ),
    ]
