# Generated by Django 2.0.5 on 2018-07-10 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_auto_20180710_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
