# Generated by Django 2.0.5 on 2018-07-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0008_auto_20180710_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='QoS',
            field=models.IntegerField(choices=[(0, 'QoS - 0'), (1, 'QoS - 1'), (2, 'QoS - 2')]),
        ),
    ]
