# Generated by Django 2.0.5 on 2018-07-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0009_auto_20180710_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='estado',
            field=models.IntegerField(choices=[(0, 'off'), (1, 'on'), (2, 'running')], default=0),
        ),
    ]
