# Generated by Django 2.0.5 on 2018-07-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0011_auto_20180710_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='estado',
            field=models.IntegerField(choices=[(0, 'off'), (1, 'iniciating'), (2, 'running'), (3, 'with problem'), (4, 'Not Conected')], default=0),
        ),
    ]
