# Generated by Django 2.0.5 on 2018-07-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0013_auto_20180710_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqtt',
            name='QoS',
            field=models.IntegerField(choices=[(0, 'QoS - 0'), (1, 'QoS - 1'), (2, 'QoS - 2')], default=0),
        ),
    ]
