# Generated by Django 2.0.5 on 2018-08-09 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0015_mqtt_rc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='status',
        ),
        migrations.AlterField(
            model_name='dado',
            name='dado',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='dado',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='dado',
            name='mqtt',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mqtt.Mqtt'),
        ),
    ]
