# Generated by Django 2.0.5 on 2018-09-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0016_auto_20180809_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqtt',
            name='topico',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
