# Generated by Django 2.0.5 on 2018-10-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atuador_boolean',
            name='task_ptr',
        ),
        migrations.RemoveField(
            model_name='atuador_troca_estado',
            name='task_ptr',
        ),
        migrations.DeleteModel(
            name='Atuador_boolean',
        ),
        migrations.DeleteModel(
            name='Atuador_troca_estado',
        ),
    ]
