# Generated by Django 2.0.5 on 2018-10-25 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_if_sensor_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='if_sensor_boolean',
            name='task_ptr',
        ),
        migrations.RemoveField(
            model_name='if_sensor_dadosensor',
            name='task_ptr',
        ),
        migrations.RemoveField(
            model_name='if_sensor_dadosensor',
            name='valor',
        ),
        migrations.RemoveField(
            model_name='if_sensor_numero',
            name='task_ptr',
        ),
        migrations.RemoveField(
            model_name='if_sensor_string',
            name='task_ptr',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_anterior',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_sucessor',
        ),
        migrations.DeleteModel(
            name='If_sensor_boolean',
        ),
        migrations.DeleteModel(
            name='If_sensor_dadosensor',
        ),
        migrations.DeleteModel(
            name='If_sensor_numero',
        ),
        migrations.DeleteModel(
            name='If_sensor_string',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
