# Generated by Django 2.0.5 on 2018-10-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0004_auto_20181007_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='is_int',
            field=models.BooleanField(default=False),
        ),
    ]
