# Generated by Django 2.0.5 on 2018-10-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt', '0006_auto_20181007_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dado',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='dispositivo',
            name='mqtt',
        ),
        migrations.DeleteModel(
            name='Dado',
        ),
        migrations.DeleteModel(
            name='Dispositivo',
        ),
    ]
