# Generated by Django 2.0.5 on 2018-10-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181021_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='json',
        ),
    ]
