# Generated by Django 2.0.5 on 2018-10-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_task_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='If_sensor_boolean',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('condicao', models.IntegerField(choices=[(0, '='), (1, '!=')])),
                ('valor', models.NullBooleanField()),
            ],
            bases=('core.task',),
        ),
    ]
