# Generated by Django 2.0.5 on 2018-10-20 11:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mqtt', '0007_auto_20181020_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QoS', models.IntegerField(choices=[(0, 'QoS - 0'), (1, 'QoS - 1'), (2, 'QoS - 2')], default=0, editable=False)),
                ('valor_char', models.CharField(blank=True, max_length=500)),
                ('valor_int', models.IntegerField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.IntegerField(choices=[(0, 'Atuador'), (1, 'Sensor')], default=0)),
                ('is_int', models.BooleanField(default=False)),
                ('mqtt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivo', to='mqtt.Mqtt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dado',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.Dispositivo'),
        ),
    ]
