# Generated by Django 2.0.5 on 2018-10-21 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181021_0933'),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atuador_boolean',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('estado', models.NullBooleanField()),
                ('atuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.Dispositivo')),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='Atuador_troca_estado',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Task')),
                ('estado_anterior', models.NullBooleanField()),
                ('estado_atual', models.NullBooleanField()),
                ('atuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarefas.Dispositivo')),
            ],
            bases=('core.task',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace', models.TextField()),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('dispositivo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='tarefas.Dispositivo')),
                ('firs_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Task')),
            ],
        ),
    ]
